language: csharp

# .NET CLI require Ubuntu 14.04
sudo: required
dist: trusty

mono: none

dotnet: 1.0.1

branches:
  only:
    - master
    - develop

script:
  - dotnet restore
  - dotnet build
  - dotnet test
