version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:
- cmd: dotnet test tests\Graph.Tests\Graph.Tests.csproj
